name: Check kernel change from docs daily and if found update Kernel Name and version 
on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

  workflow_dispatch: # Allow manual triggering
jobs:
  update_kernel_info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests
    - name: Update kernel information in script
      run: |
        python utils/update_kernel.py
    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "rahulunair@gmail.com"
        git add base/2_kernel_setup.sh
        git diff-index --quiet HEAD || git commit -m "Update kernel information"
        git push

